"""SEC source adapters."""

from .base import (
    HistoricalQuarterSource,
    RawSECRecord,
    SecOutcomeStatus,
    SecPage,
    SecProviderHealth,
    SecRawRecord,
    SECRecord,
    SecResult,
    SecSource,
)
from .daily_index import (
    DailyIndexEntry,
    SECDailyIndexSource,
    daily_index_url,
    parse_daily_master_index,
)
from .historical import (
    SEC_ARCHIVE_URL_TEMPLATE,
    archive_url,
    download_quarter,
    extract_archive,
    list_cached_quarters,
    list_quarters,
    parse_sec_tables,
    stage_quarter,
    validate_sec_user_agent,
)
from .incremental import (
    SEC_SUBMISSIONS_URL,
    IncrementalSECSource,
    SECCompanySubmissionsSource,
    SECIncrementalAdapter,
    SECIncrementalSource,
    SECRequestError,
    decode_cursor,
    encode_cursor,
)
from .parser import (
    SECParser,
    SecParser,
    parse_filing,
    parse_ownership_document,
    parse_sec_document,
    parse_sec_filing,
    parse_sec_ownership_document,
    parse_sec_xml,
)

__all__ = [
    "HistoricalQuarterSource",
    "DailyIndexEntry",
    "SECDailyIndexSource",
    "RawSECRecord",
    "SECRecord",
    "SecOutcomeStatus",
    "SecPage",
    "SecProviderHealth",
    "SecRawRecord",
    "SecResult",
    "SecSource",
    "SEC_ARCHIVE_URL_TEMPLATE",
    "archive_url",
    "download_quarter",
    "extract_archive",
    "list_cached_quarters",
    "list_quarters",
    "parse_sec_tables",
    "stage_quarter",
    "validate_sec_user_agent",
    "daily_index_url",
    "parse_daily_master_index",
    "SECIncrementalAdapter",
    "SECIncrementalSource",
    "SECCompanySubmissionsSource",
    "IncrementalSECSource",
    "SECRequestError",
    "SEC_SUBMISSIONS_URL",
    "decode_cursor",
    "encode_cursor",
    "parse_filing",
    "parse_sec_document",
    "parse_sec_filing",
    "parse_ownership_document",
    "parse_sec_ownership_document",
    "parse_sec_xml",
    "SECParser",
    "SecParser",
]
