import type { ResearchSnapshot } from '@/lib/research-v2';
import type { SettingsStatus } from '@/lib/operations-data';
import { controlClass, downloadCsv, metric, money, reasonText } from '@/lib/research';
import { isString, usePreference } from '@/lib/local-preferences';
import { SortControls, useRowSort } from './sort-controls';
import { EChart } from './echart';

export function ActivityV2({ data }: { data: ResearchSnapshot }) {
  const rows = data.economicTransactions.filter((row) => row.aggregateEligible);
  const companies = new Map(data.companies.map((row) => [row.issuerCik, row]));
  const daily = new Map<string, { buy: number; sell: number; count: number; owners: Set<string> }>();
  const sectors = new Map<string, { buy: number; sell: number; count: number; owners: Set<string> }>();
  for (const row of rows) {
    for (const [group, key] of [[daily, row.transactionDate], [sectors, companies.get(row.issuerCik)?.sector ?? 'Unmapped']] as const) {
      const value = group.get(key) ?? { buy: 0, sell: 0, count: 0, owners: new Set<string>() };
      value[row.side === 'BUY' ? 'buy' : 'sell'] += row.value ?? 0; value.count++;
      row.owners.forEach((owner) => value.owners.add(owner.ownerCik)); group.set(key, value);
    }
  }
  const days = [...daily].sort(([a], [b]) => a.localeCompare(b));
  const buys = rows.filter((row) => row.side === 'BUY');
  const sales = rows.filter((row) => row.side === 'SELL');
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Purchase value', money(buys.reduce((sum, row) => sum + (row.value ?? 0), 0))], ['Sale value', money(sales.reduce((sum, row) => sum + (row.value ?? 0), 0))], ['Economic transactions', String(rows.length)], ['Distinct reporting-owner CIKs', String(new Set(rows.flatMap((row) => row.owners.map((owner) => owner.ownerCik))).size)]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-3 font-mono text-lg">{value}</p></div>)}</div>
    <p className="text-sm leading-6 text-muted-foreground">{data.coverage.scope}. Values count each economic event once; reporting-owner counts include joint filers, not necessarily independent decisions. Unresolved-amendment issuers are excluded from these aggregates. {data.readiness.dashboard.status !== 'READY' ? 'The SEC window is incomplete; zero means no observed eligible event, not no market activity.' : ''}</p>
    <section className="rounded-xl border border-border bg-card p-5"><h2 className="text-base font-semibold">Purchases and sales by transaction date</h2>{!days.length ? <p className="mt-4 text-sm text-muted-foreground">No eligible observed events. Check coverage before interpreting the absence.</p> : <EChart style={{ height: 320 }} option={{ textStyle: { color: '#cbd5e1' }, tooltip: { trigger: 'axis' }, legend: { data: ['Purchases', 'Sales'], textStyle: { color: '#cbd5e1' } }, grid: { left: 80, right: 15, top: 50, bottom: 40 }, xAxis: { type: 'category', data: days.map(([day]) => day) }, yAxis: { type: 'value', name: 'USD', splitLine: { lineStyle: { color: '#263446' } } }, series: [{ type: 'bar', name: 'Purchases', data: days.map(([, row]) => row.buy), itemStyle: { color: '#5eead4' } }, { type: 'bar', name: 'Sales', data: days.map(([, row]) => row.sell), itemStyle: { color: '#fb7185' } }] }} />}</section>
    <section className="overflow-x-auto rounded-xl border border-border bg-card p-5"><h2 className="text-base font-semibold">Observed sector activity</h2><table className="mt-4 w-full text-left text-sm"><thead><tr>{['Sector', 'Buys USD', 'Sales USD', 'Events', 'Reporting owners'].map((label) => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{[...sectors].sort(([, a], [, b]) => b.buy - a.buy).map(([sector, row]) => <tr key={sector} className="border-t border-border"><td className="p-3">{sector}</td><td className="p-3" title={money(row.buy)}>{money(row.buy, true)}</td><td className="p-3" title={money(row.sell)}>{money(row.sell, true)}</td><td className="p-3">{row.count}</td><td className="p-3">{row.owners.size}</td></tr>)}</tbody></table></section>
  </div>;
}

export function ClustersV2({ data, openCompany, issuer }: { data: ResearchSnapshot; openCompany: (ticker: string) => void; issuer?: string }) {
  const owners = new Map(data.reportingOwners.map((row) => [row.ownerCik, row.name]));
  const companies = new Map(data.companies.map((row) => [row.issuerCik, row]));
  const events = new Map(data.economicTransactions.map((row) => [row.eventId, row]));
  const fields = [{ id: 'value', label: 'Purchase value', value: (row: ResearchSnapshot['clusters'][number]) => row.purchaseValue }, { id: 'ticker', label: 'Ticker', value: (row: ResearchSnapshot['clusters'][number]) => companies.get(row.issuerCik)?.ticker ?? row.issuerCik }];
  const sort = useRowSort(data.clusters.filter((row) => !issuer || row.issuerCik === issuer), fields, 'value', issuer ? 'lab.clusters' : 'clusters');
  return <section className="rounded-xl border border-border bg-card p-5"><h2 className="mb-2 text-base font-semibold">Verified cluster membership</h2><p className="mb-4 text-sm leading-6 text-muted-foreground">30-day purchase window. Requires disjoint reporting-owner groups in separate filings; co-reporters of the same event do not establish independent purchases.</p><SortControls fields={fields} fieldId={sort.fieldId} descending={sort.descending} onField={sort.choose} onReverse={sort.reverse} />{!sort.rows.length ? <p className="text-sm text-muted-foreground">No independently evidenced cluster in the observed window. Incomplete coverage may omit other purchases.</p> : <div className="grid gap-4 lg:grid-cols-2">{sort.rows.map((cluster) => {
    const company = companies.get(cluster.issuerCik)!;
    return <article key={cluster.clusterId} className="rounded-lg border border-border p-4"><button className="font-mono text-lg font-semibold text-emerald-200" onClick={() => openCompany(company.ticker ?? `CIK:${company.issuerCik}`)}>{company.ticker ?? company.name}</button><p className="mt-2 text-sm">{money(cluster.purchaseValue)} · {cluster.ownerCiks.length} reporting owners</p><p className="mt-1 text-xs text-muted-foreground">{cluster.start} to {cluster.end}</p><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{cluster.ownerCiks.map((cik) => <li key={cik}>{owners.get(cik)} <span className="text-xs text-muted-foreground">CIK {cik}</span></li>)}</ul><details className="mt-4 text-sm"><summary>{cluster.eventIds.length} underlying purchases</summary><ul className="mt-2 space-y-2">{cluster.eventIds.map((id) => { const row = events.get(id)!; return <li key={id}><a className="text-emerald-200 underline" href={row.sourceUrl} target="_blank" rel="noreferrer">{row.transactionDate} · {money(row.value)} · SEC row {row.rowSequence}</a></li>; })}</ul></details></article>;
  })}</div>}</section>;
}

export function BasisV2({ data, openCompany }: { data: ResearchSnapshot; openCompany: (ticker: string) => void }) {
  const [search, setSearch] = usePreference('basis.search', '', isString);
  const [days, setDays] = usePreference('basis.days', '90', isString);
  const rows = data.companies.filter((row) => `${row.ticker} ${row.name}`.toLowerCase().includes(search.toLowerCase())).map((row) => {
    const basis = row.basis.find((item) => item.days === Number(days))!;
    return { ...row, window: basis, gap: row.currentPrice == null || !basis.weightedBasis ? null : (row.currentPrice / basis.weightedBasis - 1) * 100 };
  });
  const fields = [{ id: 'costPl', label: 'Price vs basis %', value: (row: typeof rows[number]) => row.gap }, { id: 'value', label: 'Purchase value', value: (row: typeof rows[number]) => row.window.purchaseValue }, { id: 'ticker', label: 'Ticker', value: (row: typeof rows[number]) => row.ticker ?? row.issuerCik }];
  const sort = useRowSort(rows, fields, 'costPl', 'basis.v2');
  return <section className="rounded-xl border border-border bg-card p-5"><h2 className="text-base font-semibold">Observed weighted purchase basis</h2><p className="my-3 text-sm leading-6 text-muted-foreground">Sum of eligible purchase dollars / shares, counting each event once. Completeness concerns the observed SEC window, not unreported activity or total holdings. Unresolved amendments block the issuer’s basis.</p><div className="mb-4 flex flex-wrap gap-3"><input aria-label="Filter basis company" className={controlClass} placeholder="Ticker or company" value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="Basis window" className={controlClass} value={days} onChange={(event) => setDays(event.target.value)}><option value="30">30 calendar days</option><option value="90">90 calendar days</option></select><button className={controlClass} onClick={() => downloadCsv('observed-basis.csv', ['CIK', 'Ticker', 'Days', 'Basis', 'USD', 'Purchases', 'Price', 'Gap %', 'Coverage'], sort.rows.map((row) => [row.issuerCik, row.ticker, days, row.window.weightedBasis, row.window.purchaseValue, row.window.purchaseCount, row.currentPrice, row.gap, row.window.coverage]))}>Export filtered CSV</button></div><SortControls fields={fields} fieldId={sort.fieldId} descending={sort.descending} onField={sort.choose} onReverse={sort.reverse} /><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Company', 'Basis', 'Purchase USD', 'Purchases', 'Current price', 'Price vs basis', 'Coverage'].map((label) => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{sort.rows.map((row) => <tr key={row.issuerCik} className="border-t border-border"><td className="p-3"><button className="text-emerald-200" onClick={() => openCompany(row.ticker ?? `CIK:${row.issuerCik}`)}>{row.ticker ?? row.name}</button></td><td className="p-3">{money(row.window.weightedBasis)}</td><td className="p-3">{money(row.window.purchaseValue)}</td><td className="p-3">{metric(row.window.purchaseCount, 0)}</td><td className="p-3">{money(row.currentPrice)}</td><td className="p-3">{row.gap == null ? '—' : `${metric(row.gap)}%`}</td><td className="p-3 text-xs text-amber-200">{row.window.coverage === 'OBSERVED_COMPLETE_SEC_WINDOW' ? 'Observed SEC window complete' : row.window.coverage}<span className="mt-1 block text-muted-foreground">{row.window.start} – {row.window.end}</span></td></tr>)}</tbody></table></div>{!rows.length && <p className="py-4 text-sm">No companies match this filter.</p>}</section>;
}

export function CoverageV2({ data }: { data: ResearchSnapshot }) {
  const coverage = data.coverage;
  const counts = [['Discovered filings', coverage.days.reduce((sum, day) => sum + day.discoveredFilings, 0)], ['Parsed owner rows', coverage.canonicalOwnerRows], ['Economic events', coverage.economicEvents], ['Eligible P/S companies', coverage.eligibleCompanies], ['Resolved identities', coverage.resolvedIdentities], ['Priced companies', coverage.pricedCompanies], ['Complete scores', coverage.completeScores]] as const;
  return <section className="space-y-5 rounded-xl border border-border bg-card p-5"><h2 className="text-base font-semibold">Measured source-to-score coverage</h2><p className="text-sm text-muted-foreground">{coverage.scope}. Counts refer to different grains, not interchangeable denominators.</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{counts.map(([label, count]) => <div key={label} className="rounded-lg border border-border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-mono text-lg">{label === 'Discovered filings' && !coverage.days.length ? 'Unavailable' : count}</p></div>)}</div><p className="text-sm">{coverage.days.filter((day) => day.complete).length} complete SEC days / {coverage.expectedSecDays.length} expected published days. Missing: {coverage.missingSecDays.join(', ') || 'none recorded'}.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['SEC day', 'Discovered', 'Stored', 'Rows', 'Quarantine', 'Failures', 'Complete'].map((label) => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{coverage.days.map((day) => <tr key={day.day} className="border-t border-border">{[day.day, day.discoveredFilings, day.storedFilings, day.parseRows, day.quarantinedRows, day.failures, day.complete ? 'Yes' : 'No'].map((value, index) => <td key={index} className="p-2">{value}</td>)}</tr>)}</tbody></table></div><p className="text-sm">Exclusions: {Object.entries(coverage.exclusions).map(([name, count]) => `${name.replaceAll('_', ' ').toLowerCase()}: ${count}`).join(' · ')}</p></section>;
}

export function ReadinessV2({ data, digest }: { data: ResearchSnapshot; digest?: SettingsStatus['digest'] }) {
  const readiness = { ...data.readiness, digest: digest ?? data.readiness.digest };
  return <section className="grid gap-3 md:grid-cols-3">{Object.entries(readiness).map(([name, state]) => <div key={name} className="rounded-xl border border-border bg-card p-4"><h2 className="text-sm font-semibold capitalize">{name === 'predictive' ? 'Predictive model' : name === 'digest' ? 'Informational digest' : 'Factual dashboard'}</h2><p className={`my-3 font-mono text-sm ${state.status === 'READY' ? 'text-emerald-200' : 'text-amber-200'}`}>{state.status}</p>{state.reasons.map((reason) => <p key={reason} className="mt-2 text-xs text-muted-foreground">{reasonText(reason)}</p>)}</div>)}</section>;
}

export function DigestPreviewV2({ data, digest }: { data: ResearchSnapshot; digest?: SettingsStatus['digest'] }) {
  const latest = [...data.coverage.expectedSecDays].sort((a, b) => b.localeCompare(a))[0];
  const day = data.coverage.days.find((row) => row.day === latest);
  const companies = new Map(data.companies.map((row) => [row.issuerCik, row]));
  const owners = new Map(data.reportingOwners.map((row) => [row.ownerCik, row.name]));
  const rows = digest ? digest.eventIds.map((id) => data.economicTransactions.find((row) => row.eventId === id)).filter((row) => row !== undefined) : data.economicTransactions.filter((row) => row.secDay === latest && row.aggregateEligible && row.side === 'BUY' && (row.value ?? 0) >= 250000).sort((a, b) => (b.value ?? 0) - (a.value ?? 0) || a.eventId.localeCompare(b.eventId)).slice(0, 5);
  const delivery = digest ?? data.readiness.digest;
  return <section className="rounded-xl border border-border bg-card p-5">
    <h2 className="text-base font-semibold">Informational daily digest · draft preview</h2>
    <p className="my-3 text-sm leading-6 text-muted-foreground">SEC day {latest ?? 'unavailable'}. Up to five economic open-market purchases of at least $250,000, largest first; joint filers count once. No score criteria, forecasts or trading recommendations. This preview does not send a message.</p>
    <p className="mb-4 text-xs text-amber-200">Delivery: {delivery.status} · {delivery.reasons.map(reasonText).join(' · ')}</p>
    {digest && <p className="mb-4 text-xs text-muted-foreground">Server policy: {digest.enabled ? 'ON, subject to checks' : 'OFF'}. Unresolved issuers excluded: {digest.excludedIssuers ?? 'not evaluated'}. Delivery is evaluated again after a successful daily Pages publish.</p>}
    {!day?.complete ? <p className="text-sm">Preview blocked: the latest SEC day is not fully acquired and parsed. No “no new purchases” assertion can be made.</p> : !rows.length ? <p className="text-sm">No qualifying resolved purchases are currently visible for this day. Unresolved inputs can suppress an empty digest; see the delivery reasons above.</p> : <ol className="list-decimal space-y-4 pl-5">{rows.map((row) => <li key={row.eventId} className="text-sm"><a className="font-semibold text-emerald-200 underline" href={`#view=company-lab&issuer=${row.issuerCik}`}>{companies.get(row.issuerCik)?.ticker ?? companies.get(row.issuerCik)?.name} · {money(row.value)}</a><p className="mt-1 text-xs text-muted-foreground">{row.owners.map((owner) => owners.get(owner.ownerCik) ?? owner.ownerCik).join(' / ')} · Transaction {row.transactionDate}</p><a className="mt-1 inline-block text-xs text-emerald-200 underline" href={row.sourceUrl} target="_blank" rel="noreferrer">Original SEC document</a></li>)}</ol>}
  </section>;
}
